name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  powershell-core-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restore
        run: tools/restore.ps1
        shell: pwsh

      - name: test
        run: tools/run-tests.ps1 -CleanPesterAndInstallV4
        shell: pwsh 

  powershell-core-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restore
        run: tools/restore.ps1
        shell: pwsh

      - name: test
        run: tools/run-tests.ps1 -CleanPesterAndInstallV4
        shell: pwsh 

