name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  powershell-core:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Restore
        run: tools/restore.ps1
        shell: pwsh

      - name: test
        run: tools/run-tests.ps1 -CleanPesterAndInstallV4
        shell: pwsh 
  
  windows-powershell:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restore
        run: tools/restore.ps1
        shell: powershell

      - name: test
        run: tools/run-tests.ps1 -CleanPesterAndInstallV4
        shell: powershell 